spring:
  application:
    name: gestion-plus-api
  gestion:
    datasource:
      url: jdbc:postgresql://localhost:5432/bd_gestion_plus
      username: postgres
      password: pasword
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    packages-to-scan:
      - com.gestion.plus.commons.entities
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.orm.jpa: DEBUG
  mail:
    host: smtp.gmail.com 
    port: 587             
    username: admongestionplus360@gmail.com 
    password: rpvz npbk xklr zzsa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
seguridad:
  llave: keygestionplus
jwt:
  secret: L5u9mC4Qp7FJ8rXz2VpYhTtNbKwA1gD0sO3fG6ZRMIlEjcYdPoUWxvqBaHN7SKCaMnuELmasdjUENNAJSN
app:
  url:
    reset-password: http://localhost:4200/create-password

whatsapp:
 api:
   url: https://graph.facebook.com/v22.0/
 phone:
   number-id: 553326667872958
 access:
   token: EAAJwJXpBaAsBO6grmB5A0BB18RZA7ZBnPw9puwSbbZCbYeE3wsrQGANsFUVXxl2wzAZC3mJ6Ctd37YfEfyECZCCBRkqVZBB5k1t81qPJgCZC8cuF1p1JHdvBVyfkHBpw5wAHYyzsr2CrZCWJ0J3DthzCbPTh45We4LngtN7NCOaVGyt1ZADkobhjqMDgpXIUmZBwCSEZCn8VqyXvDKw8Gq9hAPqm0V6ZAZBNAYfPid6rZCb2PekCwZD